### ISSUE TITLE
Property to honor "delete" flag for unlink

### ISSUE THREAD

**Issue by tof06** [yii2tech/ar-linkmany#1]
Hi,

Love this behavior !

Would it be possible to add a property to set the `delete` flag when calling `unlink` ? 
When used on a many-to-many relation with a pivot table, I need to delete entries, not to set it to null.

Thanks

**Comment by klimov-paul** [comment]
Resolved by commit e5019c3c531a10c5bbc92c427f7a04fd26b8afe2
