### ISSUE TITLE
relationReferenceAttribute and dirtyAttributes

### ISSUE THREAD

**Issue by evgenybukharev** [yii2tech/ar-linkmany#11]
Hi,
If the contents of the relationReferenceAttribute array changes, then this attribute does not fit in dirtyAttributes, so they do not work out behaviors like TimestampBehavior, BlameableBehavior and others.
(\yii\behaviors\AttributeBehavior::evaluateAttributes)
How to be in this situation?

**Comment by klimov-paul** [comment]
There is no way, since 'dirty' attributes may refer only to the ActiveRecord table columns and can not refer to any virtual attribute, which `relationReferenceAttribute` is.
