### ISSUE TITLE
Sorted many-to-many links

### ISSUE THREAD

**Issue by ariant-web** [yii2tech/ar-linkmany#12]
I have many-to-many links. I want to sort them. Can use extra field for this? I write extra field when creating a connection. But how can update extra field for exist links? Please any example.

links TABLE actor_movie (
  actor_id int
  movie_id int
  movie_ord int
)

**Comment by klimov-paul** [comment]
You should use [yii2tech/ar-variation](https://github.com/yii2tech/ar-variation) in case you wish to store variation data per each link.
