### ISSUE TITLE
Невозможно провалидировать атрибут через EachValidator

### ISSUE THREAD

**Issue by MikhailMelnikov** [yii2tech/ar-linkmany#13]
@klimov-paul  Павел, добрый день!

https://github.com/yii2tech/ar-linkmany/blob/391dc0f4bf63e090d2d6b2117277ed8565e429d3/LinkManyBehavior.php#L96

В данной строке бехейвера принудительное  привидение аттрибута к массиву из-за этого невозможно провалидировать массив данных( массив связывания таблиц - "groupIds") через EachValildator так, как внутри валидатора в цикле аттрибуту (groupIds) присваивается значение каждого эллемента массива.

https://github.com/yiisoft/yii2/blob/dd3e5ec1e27f9fc475d41f6aeebdd5f565d813d4/framework/validators/EachValidator.php#L143

**Comment by klimov-paul** [comment]
Duplicates #9
