### ISSUE TITLE
Question for Events and blameable columns

### ISSUE THREAD

**Issue by Bhoft** [yii2tech/ar-linkmany#15]
Hi

is there a way to trigger Events on each link / unlink the models?

e.g. if i use the behavior to save the relation between a submission and a reviewer.

So after an allocation of an reviewer an email should be sent out to this newly linked reviewer.
Also some email should be sent on unlink.

Currently I only see the possibility of saving the value before and after Update and get the newly linked and relations to remove myself and use this information to create the emails.

But maybe you got some better suggestion?

Another question is there a better way to have blameable columns filled with the correct information?
Currently i fill those fields like following: 

    'extraColumns'               => [
        'reviewer_type' => self::REVIEW_TYPE_INVIVIDUAL,
        'created_at'    => function () {
            return Carbon::now('UTC')->toDateTimeString();
        },
        'updated_at'    => function () {
            return Carbon::now('UTC')->toDateTimeString();
        },
        'created_by' => function () {
            return Yii::$app->user->id;
        },
        'updated_by' => function () {
            return Yii::$app->user->id;
        },
    ],

best regards

**Comment by klimov-paul** [comment]
I can not say. You should make project decision on your own.
Since you put much logic on the relation establishment, consider to create your own high-level interface for it instead of using this extension.
