### ISSUE TITLE
FR: extra columns

### ISSUE THREAD

**Issue by alex-code** [yii2tech/ar-linkmany#2]
Could `extraColumns` be specified in the reference attribute?

``` php
$model->reference = [1 => ['extra' => 'value'], 2, 3 => ['extra' => 'other']];
```

This would be a good way to update any extra columns too where the keys stay the same.

**Comment by klimov-paul** [comment]
You may specify extra columns to be saved while linking:
https://github.com/yii2tech/ar-linkmany/blob/master/LinkManyBehavior.php#L73

If you need some automatic update you may use ActiveRecord class for the `via` in relation.

If you want to fill junction entity attributes from user input you should use [yii2tech/ar-variation](https://github.com/yii2tech/ar-variation)
