### ISSUE TITLE
Multiple saving many records

### ISSUE THREAD

**Issue by iworker** [yii2tech/ar-linkmany#3]
I tried to add this behavior for link between tables `group` and `category` using pivot table `category_group` that have columns `group_id` and `category_id`.

When I added behavior and set up "virtual property" `groupsIds`, I tried to execute request with adding one category with _three_ records from group to be related with: `groupsIds => [1,2,3]`
As expected from link method, I got three MySQL queries:

```
INSERT INTO `category_group` (`category_id`, `group_id`) VALUES (6, 1);
INSERT INTO `category_group` (`category_id`, `group_id`) VALUES (6, 2);
INSERT INTO `category_group` (`category_id`, `group_id`) VALUES (6, 3);
```

So I think it's better to use one query:

```
INSERT INTO `category_group` (`category_id`, `group_id`) VALUES (6, 1), (6, 2), (6, 3);
```

What do you think about enhancement? Is it needed or no?

**Comment by iworker** [comment]
Probably, method link must be improved for this feature..

**Comment by klimov-paul** [comment]
> Probably, method link must be improved for this feature..

Indeed. There is nothingI can do inside this project.
