### ISSUE TITLE
Saving form without related Ids

### ISSUE THREAD

**Issue by kirc0de** [yii2tech/ar-linkmany#7]
Steps to reproduce the problem:
1. Init LinkManyBehavior:

```
'linkServicesBehavior' => [
  'class' => LinkManyBehavior::className(),
  'relation' => 'salons',
  'relationReferenceAttribute' => 'salonsIds',
],
```
1. Adding 'salonIds' as `safe` attribute
2. Do not add salonIds field into `_form.php`

The problem is:
`Invalid argument supplied for foreach()` in LinkManyBehavior.php:245

Need to check if `$this->owner->{$this->relation}` isset.

**Comment by klimov-paul** [comment]
Unable to reproduce.

> The problem is: Invalid argument supplied for foreach() in LinkManyBehavior.php:245

This can not be if the behavior configured correctly: `LinkManyBehavior::relation` should refer to 'has-many' relation, which even empty is always populated as an array: empty array or array of records.

**Comment by kirc0de** [comment]
So, if i add $salonsIds public property into my model — it's ok, but there is no information in docs about this step (adding public property).

I think, that behavior add this property automatically. But in this way we have problem with missing isset() condition.

**Comment by klimov-paul** [comment]
> So, if i add $salonsIds public property into my model — it's ok, but there is no information in docs about this step (adding public property).

How does this relates to the problem? Also it is incorrect.

It looks like you do not listen to me.
