### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by webdevsega** [yii2tech/ar-linkmany#9]
When I set validation rule:
```php
['groupIds', 'each', 'rule' => ['integer']
```
always get validation error ''{attribute} must be an integer.''
Problem in line [LinkManyBehavior.php#L98](https://github.com/yii2tech/ar-linkmany/blob/master/LinkManyBehavior.php#L98)

**Comment by klimov-paul** [comment]
Resolved by commit 4a02e17b8cd6e955f72f8acd039ffed538e2d1b5
